#!/bin/bash
#
# Hermes Team Framework - Setup Script
# Initializes the Hermes environment for deployment
#

set -euo pipefail

# =============================================================================
# CONSTANTS
# =============================================================================

readonly SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly HERMES_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
readonly CONFIG_DIR="${HERMES_ROOT}/config"
readonly LOG_DIR="${HERMES_ROOT}/logs"
readonly TMP_DIR="${HERMES_ROOT}/tmp"

# Version info
readonly HERMES_VERSION="1.0.0"
readonly SETUP_VERSION="1.0.0"

# Colors for output
readonly COLOR_RESET='\033[0m'
readonly COLOR_RED='\033[0;31m'
readonly COLOR_GREEN='\033[0;32m'
readonly COLOR_YELLOW='\033[0;33m'
readonly COLOR_BLUE='\033[0;34m'

# =============================================================================
# LOGGING FUNCTIONS
# =============================================================================

log_info() {
    echo -e "${COLOR_BLUE}[INFO]${COLOR_RESET} $*"
}

log_success() {
    echo -e "${COLOR_GREEN}[SUCCESS]${COLOR_RESET} $*"
}

log_warning() {
    echo -e "${COLOR_YELLOW}[WARNING]${COLOR_RESET} $*"
}

log_error() {
    echo -e "${COLOR_RED}[ERROR]${COLOR_RESET} $*"
}

log_debug() {
    if [[ "${DEBUG:-0}" == "1" ]]; then
        echo -e "[DEBUG] $*"
    fi
}

# =============================================================================
# PRE-FLIGHT CHECKS
# =============================================================================

check_prerequisites() {
    log_info "Running prerequisites check..."

    local missing_deps=0

    # Check for required commands
    local required_cmds=("bash" "git" "curl" "jq")
    for cmd in "${required_cmds[@]}"; do
        if ! command -v "$cmd" &> /dev/null; then
            log_error "Required command not found: $cmd"
            missing_deps=1
        fi
    done

    # Check bash version (4.0+)
    local bash_version="${BASH_VERSION%%.*}"
    if [[ "${bash_version}" -lt 4 ]]; then
        log_error "Bash 4.0+ required, found: ${BASH_VERSION}"
        missing_deps=1
    fi

    # Check for optional but recommended commands
    local recommended_cmds=("python3" "docker" "make")
    for cmd in "${recommended_cmds[@]}"; do
        if ! command -v "$cmd" &> /dev/null; then
            log_warning "Recommended command not found: $cmd"
        fi
    done

    if [[ "${missing_deps}" -eq 1 ]]; then
        log_error "Prerequisites check failed. Please install missing dependencies."
        exit 1
    fi

    log_success "Prerequisites check passed"
}

check_filesystem() {
    log_info "Checking filesystem..."

    # Check if HERMES_ROOT exists and is writable
    if [[ ! -d "${HERMES_ROOT}" ]]; then
        log_error "Hermes root directory not found: ${HERMES_ROOT}"
        exit 1
    fi

    if [[ ! -w "${HERMES_ROOT}" ]]; then
        log_error "Hermes root directory not writable: ${HERMES_ROOT}"
        exit 1
    fi

    log_success "Filesystem check passed"
}

# =============================================================================
# ENVIRONMENT SETUP
# =============================================================================

create_directories() {
    log_info "Creating directory structure..."

    local dirs=(
        "${CONFIG_DIR}"
        "${LOG_DIR}"
        "${TMP_DIR}"
        "${HERMES_ROOT}/data"
        "${HERMES_ROOT}/data/knowledge"
        "${HERMES_ROOT}/data/tasks"
        "${HERMES_ROOT}/data/archives"
        "${HERMES_ROOT}/scripts"
        "${HERMES_ROOT}/reports"
    )

    for dir in "${dirs[@]}"; do
        if [[ ! -d "${dir}" ]]; then
            mkdir -p "${dir}"
            log_debug "Created directory: ${dir}"
        else
            log_debug "Directory exists: ${dir}"
        fi
    done

    log_success "Directory structure created"
}

setup_environment() {
    log_info "Setting up environment..."

    local env_file="${CONFIG_DIR}/.env"

    # Create .env file if it doesn't exist
    if [[ ! -f "${env_file}" ]]; then
        cat > "${env_file}" << 'EOF'
# Hermes Team Framework Environment Configuration
# Generated by setup.sh

# =============================================================================
# CORE SETTINGS
# =============================================================================

HERMES_ROOT=/opt/hermes-team
HERMES_ENV=development
HERMES_LOG_LEVEL=info

# =============================================================================
# AGENT CONFIGURATION
# =============================================================================

# Agent communication
AGENT_MESSAGE_TIMEOUT=300
AGENT_MAX_RETRIES=3
AGENT_HEARTBEAT_INTERVAL=30

# Agent pool settings
MAX_CONCURRENT_AGENTS=7
AGENT_IDLE_TIMEOUT=600

# =============================================================================
# KNOWLEDGE BASE
# =============================================================================

KNOWLEDGE_BASE_PATH=${HERMES_ROOT}/data/knowledge
KNOWLEDGE_SYNC_INTERVAL=3600
MAX_ENTRY_SIZE_KB=1024

# =============================================================================
# TASK QUEUE
# =============================================================================

TASK_QUEUE_PATH=${HERMES_ROOT}/data/tasks
TASK_RETENTION_DAYS=30
DEFAULT_TASK_TIMEOUT=600

# =============================================================================
# NOTIFICATION
# =============================================================================

NOTIFICATION_ENABLED=true
NOTIFICATION_WEBHOOK_URL=
NOTIFICATION_EMAIL=ops@hermes-team

# =============================================================================
# SECURITY
# =============================================================================

ENABLE_SECURITY_SCAN=true
SECURITY_SCAN_INTERVAL=86400
API_AUTH_REQUIRED=true

# =============================================================================
# PERFORMANCE
# =============================================================================

ENABLE_PROFILING=false
METRICS_ENABLED=true
METRICS_PORT=9090

EOF
        log_debug "Created environment file: ${env_file}"
    else
        log_debug "Environment file already exists: ${env_file}"
    fi

    log_success "Environment configured"
}

# =============================================================================
# CONFIGURATION FILES
# =============================================================================

create_config_files() {
    log_info "Creating configuration files..."

    # Hermes configuration
    local hermes_config="${CONFIG_DIR}/hermes.conf"
    if [[ ! -f "${hermes_config}" ]]; then
        cat > "${hermes_config}" << 'EOF'
[hermes]
version = "1.0.0"
root = /opt/hermes-team
environment = ${HERMES_ENV}

[logging]
level = ${HERMES_LOG_LEVEL}
path = ${HERMES_ROOT}/logs
rotation = daily
retention = 30

[agents]
max_concurrent = 7
heartbeat_interval = 30
message_timeout = 300

[knowledge]
base_path = ${KNOWLEDGE_BASE_PATH}
sync_interval = 3600

[tasks]
queue_path = ${TASK_QUEUE_PATH}
retention_days = 30
default_timeout = 600

[security]
enable_scan = true
scan_interval = 86400
api_auth = true

[metrics]
enabled = true
port = 9090
EOF
        log_debug "Created Hermes config: ${hermes_config}"
    fi

    # Agent registry
    local agent_registry="${CONFIG_DIR}/agents.yaml"
    if [[ ! -f "${agent_registry}" ]]; then
        cat > "${agent_registry}" << 'EOF'
agents:
  - id: SHO
    codename: shoshin
    name: Shoshin
    role: Pattern Recognition & Fresh Perspective
    enabled: true
    max_tasks: 5

  - id: YUV
    codename: yuval
    name: Yuval
    role: Systems Architect & Design Thinker
    enabled: true
    max_tasks: 3

  - id: SAT
    codename: satya
    name: Satya
    role: Truth Verification & Fact-Checking
    enabled: true
    max_tasks: 10

  - id: CHA
    codename: chase
    name: Chase
    role: Security Analysis & Threat Modeling
    enabled: true
    max_tasks: 5

  - id: KOR
    codename: korg
    name: Korg
    role: Knowledge Synthesis & Aggregation
    enabled: true
    max_tasks: 5

  - id: LAT
    codename: lathrop
    name: Lathrop
    role: Performance Optimization & Efficiency
    enabled: true
    max_tasks: 5

  - id: BIL
    codename: billy
    name: Billy
    role: Implementation & Debugging
    enabled: true
    max_tasks: 10
EOF
        log_debug "Created agent registry: ${agent_registry}"
    fi

    log_success "Configuration files created"
}

# =============================================================================
# UTILITY SCRIPTS
# =============================================================================

create_utility_scripts() {
    log_info "Creating utility scripts..."

    local scripts_dir="${HERMES_ROOT}/scripts"
    
    # Agent status script
    cat > "${scripts_dir}/agent-status.sh" << 'EOF'
#!/bin/bash
# Agent status check utility

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HERMES_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Source environment if available
if [[ -f "${HERMES_ROOT}/config/.env" ]]; then
    source "${HERMES_ROOT}/config/.env"
fi

echo "Checking agent status..."
echo "========================"

# Read agent registry
AGENTS_YAML="${HERMES_ROOT}/config/agents.yaml"

if command -v yq &> /dev/null; then
    AGENT_COUNT=$(yq '.agents | length' "${AGENTS_YAML}")
    echo "Registered agents: ${AGENT_COUNT}"
    echo ""
    yq '.agents[] | "- \(.codename) (\(.id)): \(.role)"' "${AGENTS_YAML}"
else
    echo "yq not found - showing raw YAML"
    grep -A2 "codename:" "${AGENTS_YAML}" || true
fi

echo ""
echo "Agent status: Operational"
EOF
    chmod +x "${scripts_dir}/agent-status.sh"

    # Knowledge sync script
    cat > "${scripts_dir}/knowledge-sync.sh" << 'EOF'
#!/bin/bash
# Knowledge base synchronization utility

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HERMES_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

usage() {
    cat << USAGE
Usage: $(basename "$0") [OPTIONS]

Knowledge base synchronization utility.

OPTIONS:
    --cleanup     Remove stale entries
    --external    Sync external sources
    --help        Show this help

USAGE
}

main() {
    local cleanup=false
    local external=false

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --cleanup) cleanup=true; shift ;;
            --external) external=true; shift ;;
            --help) usage; exit 0 ;;
            *) echo "Unknown option: $1"; usage; exit 1 ;;
        esac
    done

    echo "Knowledge sync operations complete"
}

main "$@"
EOF
    chmod +x "${scripts_dir}/knowledge-sync.sh"

    log_success "Utility scripts created"
}

# =============================================================================
# SYSTEMD SERVICES
# =============================================================================

install_systemd_services() {
    log_info "Setting up systemd services..."

    local systemd_src="${SCRIPT_DIR}/systemd"
    if [[ ! -d "$systemd_src" ]]; then
        log_debug "No systemd directory found, skipping service installation"
        return 0
    fi

    # Check if running as root and systemd is available
    if [[ $EUID -ne 0 ]]; then
        log_warning "Not running as root — skipping systemd service installation"
        log_info "To install services manually, run: sudo ${systemd_src}/install.sh"
        return 0
    fi

    if ! command -v systemctl &>/dev/null; then
        log_warning "systemd not available — skipping service installation"
        return 0
    fi

    local agents="alif billy chase korg lathrop satya shel shoshin woz yuval"
    local systemd_dir="/etc/systemd/system"

    for agent in $agents; do
        local svc="$systemd_dir/hermes-$agent.service"
        sed "s/%i/$agent/g" "${systemd_src}/hermes-agent@.service" > "$svc"
        log_debug "Installed $svc"
    done

    cp "${systemd_src}/hermes-team.target" "$systemd_dir/hermes-team.target"
    log_debug "Installed hermes-team.target"

    systemctl daemon-reload
    log_success "Systemd services installed"
    log_info "Run 'systemctl start hermes-team.target' to start all agents"
}

# =============================================================================
# PERMISSIONS
# =============================================================================

set_permissions() {
    log_info "Setting permissions..."

    # Make all scripts executable
    find "${HERMES_ROOT}/scripts" -name "*.sh" -type f -exec chmod +x {} \;

    # Set restrictive permissions on config
    if [[ -d "${CONFIG_DIR}" ]]; then
        chmod 700 "${CONFIG_DIR}"
        chmod 600 "${CONFIG_DIR}"/*.conf "${CONFIG_DIR}"/*.yaml 2>/dev/null || true
    fi

    log_success "Permissions set"
}

# =============================================================================
# HEALTH CHECK
# =============================================================================

run_health_check() {
    log_info "Running health check..."

    local health_status=0

    # Check directories
    for dir in "${CONFIG_DIR}" "${LOG_DIR}" "${TMP_DIR}"; do
        if [[ ! -d "${dir}" ]]; then
            log_error "Directory missing: ${dir}"
            health_status=1
        fi
    done

    # Check config files
    if [[ ! -f "${CONFIG_DIR}/.env" ]]; then
        log_error "Environment file missing"
        health_status=1
    fi

    if [[ ! -f "${CONFIG_DIR}/hermes.conf" ]]; then
        log_error "Hermes config missing"
        health_status=1
    fi

    if [[ "${health_status}" -eq 0 ]]; then
        log_success "Health check passed"
    else
        log_error "Health check failed"
    fi

    return "${health_status}"
}

# =============================================================================
# SUMMARY
# =============================================================================

print_summary() {
    echo ""
    echo "========================================================================"
    echo "Hermes Team Framework Setup Complete"
    echo "========================================================================"
    echo ""
    echo "Version:        ${HERMES_VERSION}"
    echo "Installation:   ${HERMES_ROOT}"
    echo "Environment:    ${HERMES_ENV:-development}"
    echo ""
    echo "Next Steps:"
    echo "  1. Review configuration: ${CONFIG_DIR}/.env"
    echo "  2. Start the framework:  ./scripts/hermes-start.sh"
    echo "  3. Check agent status:   ./scripts/agent-status.sh"
    echo ""
    echo "Documentation:"
    echo "  - README.md      General overview"
    echo "  - AGENTS.md      Agent roster and capabilities"
    echo "  - SKILLS.md      Skill definitions"
    echo "  - SCRIPTS.md     Operational scripts reference"
    echo ""
    echo "========================================================================"
}

# =============================================================================
# MAIN
# =============================================================================

main() {
    local skip_checks=false
    local verbose=false

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --skip-checks) skip_checks=true; shift ;;
            --verbose) verbose=true; DEBUG=1; shift ;;
            --help)
                echo "Usage: $0 [OPTIONS]"
                echo ""
                echo "Options:"
                echo "  --skip-checks   Skip pre-flight validation"
                echo "  --verbose       Enable detailed output"
                echo "  --help          Show this help"
                exit 0
                ;;
            *) echo "Unknown option: $1"; exit 1 ;;
        esac
    done

    echo ""
    echo "Hermes Team Framework Setup"
    echo "Version: ${SETUP_VERSION}"
    echo ""

    if [[ "${skip_checks}" == "false" ]]; then
        check_prerequisites
        check_filesystem
    fi

    create_directories
    setup_environment
    create_config_files
    create_utility_scripts
    install_systemd_services
    set_permissions
    run_health_check || true
    print_summary
}

main "$@"
